<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WebMatias_MVC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Imagenes\ImagenesEmpresas\" />
    <Folder Include="wwwroot\Imagenes\ImagenesSobremi\" />
  </ItemGroup>

</Project>
